### ISSUE TITLE
Build on macOS Sequoia 15.6 is failing

### ISSUE THREAD

**Issue by fitzner** [bazelbuild/remote-apis-sdks#627]
Build of the remote-apis-sdks tooling is failing on macOS Sequoia 15.6 with the following error:

```
In file included from external/zlib/zutil.c:10:
In file included from external/zlib/gzguts.h:21:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdio.h:61:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_stdio.h:318:7: error: expected ')'
```

Compiler:
```
Homebrew clang version 20.1.8
Target: arm64-apple-darwin24.6.0
```

The problem seems to be related to the zlib (1.2.11) version used as a dependency.

Have you found anything relevant by searching the web?
- https://github.com/bazelbuild/bazel/issues/25124
- https://github.com/mesop-dev/mesop/issues/1277
